<center>
    <tr>
    <td><img src="ontario-tech-univ-logo.png" width="25%"></img></td>
    </tr>
</center>

# Image formation and pinhole camera model - Workbook

Faisal Qureshi   
Professor    
Faculty of Science    
Ontario Tech University    
Oshawa ON Canada    
http://vclab.science.ontariotechu.ca

In [1]:
import numpy as np
import math
from scipy import linalg

## Exercise: determining camera parameters from a projection matrix

(This is example 6.2 from [Multiple View Geometry in Computer Vision (2nd Ed.)](https://www.robots.ox.ac.uk/~vgg/hzbook/) by Harley and Zisserman)

Suppose we are given a projection matrix $\mathtt{P}$ as follows:

$$
\mathtt{P} = \begin{bmatrix}
3.53553\times10^{2} & 3.39645\times10^{2} & 2.77744\times10^{2} & -1.44946\times10^{6} \\
-1.03528\times10^{2} & 2.33212\times10^{1} & 4.59607\times10^{2} &-6.32525\times10^{5} \\
7.07107\times10^{-1} & -3.53553\times10^{-1} & 6.12372\times10^{-1} & -9.18559\times10^{2}
\end{bmatrix}
$$
Use $\mathtt{P}$ as given above to find the camera centre, the rotation, and the intrinsic parameters.

In [3]:
P = np.array([[3.53553e2, 3.39645e2, 2.77744e2, -1.44946e6],
              [-1.03528e2, 2.33212e1, 4.59607e2, -6.32525e5],
              [7.07107e-1, -3.53553e-1, 6.12372e-1, -9.18559e2]]) 

In [5]:
# Your solution here
M = P[:3,:3]
print(f'M = {M}')

M_inv = np.linalg.inv(M)
print(f'M_inv = {M_inv}')

p_4 = P[:,-1]
print(f'p_4 = {p_4}')

C = - np.dot(M_inv, p_4)
print(f'Center of this camera is {C}')

M = [[ 3.53553e+02  3.39645e+02  2.77744e+02]
 [-1.03528e+02  2.33212e+01  4.59607e+02]
 [ 7.07107e-01 -3.53553e-01  6.12372e-01]]
M_inv = [[ 8.83882084e-04 -1.53092925e-03  7.48128351e-01]
 [ 1.94194195e-03  1.00556004e-04 -9.56247129e-01]
 [ 1.00560104e-04  1.82582265e-03  2.17039911e-01]]
p_4 = [-1.44946e+06 -6.32525e+05 -9.18559e+02]
Center of this camera is [1000.00073079 2000.001952   1500.00028314]


M is given, how to find K and R? Ans: RQ decomposition.    

In [7]:
K, R = linalg.rq(M)

print(f'K = {K}')
print(f'R = {R}')

K = [[ 468.16467128  -91.22505222 -300.00001631]
 [   0.         -427.20086371 -199.99985412]
 [   0.            0.           -0.99999975]]
R = [[ 0.41380237  0.90914861  0.04707869]
 [ 0.57338211 -0.22011137 -0.78916661]
 [-0.70710718  0.35355309 -0.61237215]]


In [ ]:
np.isclose(np.dot(R[:,0], R[:,1]), 0)

In [ ]:
np.dot(R, R.T)

In [8]:
K

array([[ 468.16467128,  -91.22505222, -300.00001631],
       [   0.        , -427.20086371, -199.99985412],
       [   0.        ,    0.        ,   -0.99999975]])

In [9]:
np.diag(K)

array([ 468.16467128, -427.20086371,   -0.99999975])

In [ ]:
np.sign(np.diag(K))

In [11]:
FOO = np.diag(np.sign(np.diag(K)))
print(f'FOO = {FOO}')

FOO = [[ 1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0. -1.]]


In [12]:
np.dot(FOO, FOO) # FORTRAN IDENTITY

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

M = K R = (K FOO) (FOO R)

In [13]:
new_K = np.dot(K, FOO)
print(f'new_K = {new_K}')

new_K = [[468.16467128  91.22505222 300.00001631]
 [  0.         427.20086371 199.99985412]
 [  0.           0.           0.99999975]]


In [14]:
new_R = np.dot(FOO, R)
print(f'new_R = {new_R}')

new_R = [[ 0.41380237  0.90914861  0.04707869]
 [-0.57338211  0.22011137  0.78916661]
 [ 0.70710718 -0.35355309  0.61237215]]
