## Exercise 1
Compute Cosine and Euclidean distance matrix between three vectors  [1,0,0] ,  [0,1,0] ,  [1,1,0] , and  [10,−2,1] 

In [13]:
# %load solutions/local-features/solution-01.py
from scipy.spatial import distance
import numpy as np

a = np.array([1,0,0])
b = np.array([0,1,0])
c = np.array([1,1,0])
d = np.array([10,-2,1])

# Set up a m-by-n matrix, where m is the number of
# data items and n is the dimension

X = np.vstack((a,b,c,d))
print(f'Shape of X is {X.shape}')
print(X)

# D is condensed matrix
metric = ['cosine', 'euclidean']
#i = 0 #for cosine distance
i = 1 #for euclidean distance
D = distance.pdist(X, metric[i])

#Lets convert it into square form
print(f'{metric[i]} distance')
print(1.0 - distance.squareform(D))

Shape of X is (4, 3)
[[ 1  0  0]
 [ 0  1  0]
 [ 1  1  0]
 [10 -2  1]]
euclidean distance
[[ 1.         -0.41421356  0.         -8.2736185 ]
 [-0.41421356  1.          0.         -9.48808848]
 [ 0.          0.          1.         -8.53939201]
 [-8.2736185  -9.48808848 -8.53939201  1.        ]]


## Exercise 2
Compute Cosine similarity matrix between  [1,0,0] ,  [0,1,0] ,  [1,1,0] , and  [10,−2,1] 

In [7]:
# %load solutions/local-features/solution-02.py
from scipy.spatial import distance
import numpy as np

a = np.array([1,0,0])
b = np.array([0,1,0])
c = np.array([1,1,0])
d = np.array([10,-2,1])

# Set up a m-by-n matrix, where m is the number of
# data items and n is the dimension

X = np.vstack((a,b,c,d))
print(f'Shape of X is {X.shape}')
print(X)

# D is condensed matrix
metric = ['cosine', 'euclidean']
#i = 0 #for cosine distance
i = 1 #for euclidean distance
D = distance.pdist(X, metric[i])

#Lets convert it into square form
print(f'{metric[i]} similarity')
print(1.0 - distance.squareform(D))

Shape of X is (4, 3)
[[ 1  0  0]
 [ 0  1  0]
 [ 1  1  0]
 [10 -2  1]]
euclidean similarity
[[ 1.         -0.41421356  0.         -8.2736185 ]
 [-0.41421356  1.          0.         -9.48808848]
 [ 0.          0.          1.         -8.53939201]
 [-8.2736185  -9.48808848 -8.53939201  1.        ]]


## Exercise 3
Compute similarity matrix between  [1,0,0] ,  [0,1,0] ,  [1,1,0] , and  [10,−2,1] . Assume Euclidean distance metric.

In [12]:
# %load solutions/local-features/solution-03.py
from scipy.spatial import distance
import numpy as np

a = np.array([1,0,0])
b = np.array([0,1,0])
c = np.array([1,1,0])
d = np.array([10,-2,1])

# Set up a m-by-n matrix, where m is the number of
# data items and n is the dimension

X = np.vstack((a,b,c,d))
#print(f'Shape of X is {X.shape}')
#print(X)

# D is condensed matrix
metric = ['cosine', 'euclidean']
#i = 0
i = 1 
D = distance.squareform(distance.pdist(X, metric[i]))
print('Distance:\n', D)

#Lets convert it into square form
sigma = 0.0001
scaling = 2 * (sigma ** 2)


print(f'{metric[i]} similarity')
np.set_printoptions(formatter={'float': lambda x: "{0:0.1e}".format(x)})
S = np.exp(-D**2 / (scaling))

print('Similarity:\n', S)
np.set_printoptions() #To not mess with other printing

Distance:
 [[ 0.          1.41421356  1.          9.2736185 ]
 [ 1.41421356  0.          1.         10.48808848]
 [ 1.          1.          0.          9.53939201]
 [ 9.2736185  10.48808848  9.53939201  0.        ]]
euclidean similarity
Similarity:
 [[1.0e+00 0.0e+00 0.0e+00 0.0e+00]
 [0.0e+00 1.0e+00 0.0e+00 0.0e+00]
 [0.0e+00 0.0e+00 1.0e+00 0.0e+00]
 [0.0e+00 0.0e+00 0.0e+00 1.0e+00]]


## KDTree data structure